### ISSUE TITLE
update.json wrong format

### ISSUE THREAD

**Issue by mohamad-supangat** [xerta555/CloudflareDNS4Magisk#1]
do you not understand the correct way of writing json ??

![image](https://user-images.githubusercontent.com/48933993/152458522-d8d581ba-0264-4f40-bec4-5be715f29118.png)
the correct writing is

```json
{
    "version": "v2.7",
    "versionCode": 27,
    "zipUrl": "https://github.com/xerta555/CloudflareDNS4Magisk/releases/download/2.7/CloudflareDNS4Magisk-2.7.zip",
    "changelog": "Update to Magisk v24"
}
```

not

```json
{
    "version": v2.7,
    "versionCode": 27,
    "zipUrl": https://github.com/xerta555/CloudflareDNS4Magisk/releases/download/2.7/CloudflareDNS4Magisk-2.7.zip,
    "changelog": Update to Magisk v24
}
```

**Comment by xerta555** [comment]
Comparring the official doc at https://github.com/topjohnwu/Magisk/blob/master/docs/guides.md i don't see `"` symbols
![image](https://user-images.githubusercontent.com/20888017/152572882-adb3f928-0b39-4a56-b7d4-b35764d84c14.png)

**Comment by mohamad-supangat** [comment]
that is an example, and for correct json format if value is string is to use "

take a look at some references in other modules
https://github.com/Magisk-Modules-Alt-Repo/SystemlessDebloater/blob/554a34cd033f39220c42c4b3ae7c6f8f0959489b/update.json#L1-L6

**Comment by xerta555** [comment]
> that is an example, and for correct json format if value is string is to use "
> 
> take a look at some references in other modules [Magisk-Modules-Alt-Repo/SystemlessDebloater@`554a34c`/update.json#L1-L6](https://github.com/Magisk-Modules-Alt-Repo/SystemlessDebloater/blob/554a34cd033f39220c42c4b3ae7c6f8f0959489b/update.json#L1-L6)

I confused the module.prop files with the update.json file, so i made the necessary corrections.
